# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-12 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='server',
        ),
        migrations.RemoveField(
            model_name='server',
            name='address',
        ),
        migrations.RemoveField(
            model_name='server',
            name='data',
        ),
        migrations.RemoveField(
            model_name='server',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='server',
            name='refresh_batch',
        ),
        migrations.RemoveField(
            model_name='server',
            name='response',
        ),
        migrations.RemoveField(
            model_name='serverdata',
            name='engine_version',
        ),
        migrations.RemoveField(
            model_name='serverdata',
            name='game_mode',
        ),
        migrations.RemoveField(
            model_name='serverdata',
            name='iwad',
        ),
        migrations.RemoveField(
            model_name='serverdata',
            name='mapname',
        ),
        migrations.RemoveField(
            model_name='serverdata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='serverdata',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='serverdmflagsgroup',
            name='dmflags',
        ),
        migrations.RemoveField(
            model_name='serverdmflagsgroup',
            name='server_data',
        ),
        migrations.RemoveField(
            model_name='servergamefile',
            name='gamefile',
        ),
        migrations.RemoveField(
            model_name='servergamefile',
            name='server_data',
        ),
        migrations.RemoveField(
            model_name='servermodifier',
            name='cvar',
        ),
        migrations.RemoveField(
            model_name='servermodifier',
            name='server_data',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Cvar',
        ),
        migrations.DeleteModel(
            name='DmflagsGroup',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.DeleteModel(
            name='ServerData',
        ),
        migrations.DeleteModel(
            name='ServerDmflagsGroup',
        ),
        migrations.DeleteModel(
            name='ServerGameFile',
        ),
        migrations.DeleteModel(
            name='ServerModifier',
        ),
        migrations.DeleteModel(
            name='ServerResponse',
        ),
    ]
