# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-12 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import sys


def server_granularize(apps, schema_editor):
    n = 0
    ServerPopularity = apps.get_model('presentation', 'ServerPopularity')
    page_size = 1000
    total = ServerPopularity.objects.count()
    print >>sys.stderr, "Gonna translate {} records".format(total)
    for page in range(0, total, page_size):
        for pop in ServerPopularity.objects.order_by("id").all().prefetch_related(
                "server__data__name")[page:page + page_size]:
            n += 1
            if (n % 10000) == 0:
                print >>sys.stderr, "Progress: {}".format(n)
            pop.engine = pop.server.engine
            pop.server_name = pop.server.data.name
            pop.save()


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0004_iwadpopularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverpopularity',
            name='server_name',
            field=models.ForeignKey(to='stats.Name', null=True)
        ),
        migrations.AddField(
            model_name='serverpopularity',
            name='engine',
            field=models.ForeignKey(to='stats.Engine', null=True)
        ),
        migrations.RunPython(server_granularize),
        migrations.AlterField(
            model_name='serverpopularity',
            name='server_name',
            field=models.ForeignKey(to='stats.Name', null=False),
        ),
        migrations.AlterField(
            model_name='serverpopularity',
            name='engine',
            field=models.ForeignKey(to='stats.Engine', null=False),
        ),
        migrations.RemoveField(
            model_name='serverpopularity',
            name='server'
        ),
    ]
